model:
  resume: False #True #False #True
  amp: True
  base_learning_rate: 4.0e-5
  params:
    embed_dim: 4
    label_conc: 128
    lossconfig:
      params:
        disc_start: 100000000
# model:
#   resume: False #True #False #True
#   amp: True
#   base_learning_rate: 4.0e-5
#   params:
#     embed_dim: 16
#     label_conc: 128
#     lossconfig:
#       params:
#         disc_start: 100000000

    ddconfig:
      double_z: False
      channels: 32
      resolution: 128
      timesteps: 16
      skip: 1
      in_channels: 1
      out_ch: 1
      num_res_blocks: 2 # num_res_blocks: 2
      attn_resolutions: []
      splits: 1
      label_conc: 128
    # ddconfig:
    #   double_z: False
    #   channels: 16
    #   resolution: 128
    #   timesteps: 16
    #   skip: 1
    #   in_channels: 1
    #   out_ch: 1
    #   num_res_blocks: 1 # num_res_blocks: 2
    #   attn_resolutions: []
    #   splits: 1
    #   label_conc: 128
